### PR TITLE
[WIP] Use upstream Kubernetes gRPC Health Check feature

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Experimental PR to test/implement https://github.com/GoogleCloudPlatform/microservices-demo/issues/662

This won't work with the current GKE cluster used in CI because it's GKE < 1.24.

In order to test this, you could provision a GKE cluster in 1.24:
```
gcloud container clusters create test-grpc \
    --release-channel=rapid \
    --cluster-version=1.24
```
_Note: Not an option with 1.23 because it's in alpha and forces users to enable alpha features flag on their Kubernetes clusters._

- [ ] Test on GKE 1.24
- [ ] Validate approach for a potential future merge into `main`
- [ ] Run image scanning to see differences in terms of CVEs (`docker run aquasec/trivy image`)
- [ ] Update CI's + OB Live's GKE clusters to 1.24 to make sure everything works

Once tested/approved, but before thinking about merging it, what are we going to do with this PR?

If we want to support Kubernetes < 1.24 we need to:
1. either have 2 containers (one with the old bin and the other without) + some Kustomize or Helm or manifests duplication - not ideal here...
2. or wait for the end of life of 1.23 as an example which is planned for 2023-02-28 ([source](https://kubernetes.io/releases/#release-history) and [source](https://endoflife.date/kubernetes)). Apparently for GKE it's 2023-06 ([source](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule_for_release_channels))

I think 2. is a fair option if we could say that starting 2023-02-28 (or 2023-06) Online Boutique will only work on Kubernetes 1.24+ moving forward?

Complementary information:

## Image size locally
- `emailservice`: -24%
  - `gcr.io/google-samples/microservices-demo/emailservice:v0.3.8`: 220MB
  - `gcr.io/online-boutique-ci/refs/pull/849/emailservice:849`: 190MB
- `paymentservice`: -7%
  - `gcr.io/google-samples/microservices-demo/paymentservice:v0.3.8`: 162MB
  - `gcr.io/online-boutique-ci/refs/pull/849/paymentservice:849`: 151MB
- `cartservice`: -18%
  - `gcr.io/google-samples/microservices-demo/cartservice:v0.3.8`: 62.1MB
  - `gcr.io/online-boutique-ci/refs/pull/849/cartservice:849`: 51.2MB

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Yep, agreed. Option 2 seems to makes more sense.

As for the version, yep we shouldn't align this with 1.23, because the feature is in `alpha` and the Kubernetes cluster needs to enable `alpha` features, not very convenient. That's why I mentioned the alignment with 1.24.

To answer your question:
> how much value are we creating by demo-ing the feature on Online Boutique?

Top of mind, here are the reasons we should do it whenever we decide it's the right (less disruptive) time:
- Use upstream/native Kubernetes features and show best practice associated to grpc microservices
- Decrease the size and the surface of attack of the containers by integrating a bin tool in every container (for that, I will provide the before/after info about size and CVEs in the main description later)
- Avoid maintaining/updating the version of this bin embedded in every container
- Mitigate the fact that the project associated to this bin is not going to be maintained (personal assumption here) in the future (Xoogler) + this bin was doing anyway more than what we need (simple health check on the port)

**Comment by NimJay** [comment]
I think just waiting for `1.24` to be default on GKE's `STABLE` channel should suffice. Like you hinted at, the 5-month footprint might be minor.
Also, thank you for listing out the value of this change. That helps!

We shall keep this PR open for now.

**Comment by mathieu-benoit** [comment]
Note for myself for next rotation, let's update this PR with:
- Merge from `main` and resolve conflicts
- Update next steps based on the fact that GKE 1.25 is now in `Rapid` channel: https://cloud.google.com/kubernetes-engine/docs/release-notes#September_14_2022

**Comment by mathieu-benoit** [comment]
Closing this experimental research and tests, first concrete implementation of this there now: https://github.com/GoogleCloudPlatform/microservices-demo/pull/1102

**Pull request closed without merging**
