### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Support IPv6 on single-stack clusters.

2 issues are fixed:
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/599
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/1221.

We set `[::]` instead of `0.0.0.0` and will see from there. It seems that `[::]` works for both stacks: IPv4 and IPv6 (the app on our GKE-IPv4 test environment here http://34.27.51.101/ is still working). It was already the case in the code for `recommendationservice` and `emailservice`:
- https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/recommendationservice/recommendation_server.py#L143
- https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/emailservice/email_server.py#L130

For the `StackExchange.Redis` issue, we need to add a direct dependency to `StackExchange.Redis`. See https://github.com/dotnet/aspnetcore/issues/45424.

**How to test this?** Good question, you just have to deploy the following images:
- `gcr.io/online-boutique-ci/refs/pull/1340/paymentservice:1340`
- `gcr.io/online-boutique-ci/refs/pull/1340/cartservice:1340`
- `gcr.io/online-boutique-ci/refs/pull/1340/currencyservice:1340`
- `gcr.io/online-boutique-ci/refs/pull/1340/emailservice:1340`

Also, capturing some findings/learnings/pointers here too:
- https://stackoverflow.com/questions/27480094/ipv6-is-equivalent-to-0-0-0-0-when-listening-for-connections
- https://www.grouparoo.com/blog/node-js-and-ipv6#ipv6-also-support-ipv4-addresses
- [GKE in dual-stack mode](https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#dual_stack_network), so we can't test the single-stack IPv6 scenario with GKE, apparently.

### CODE REVIEW

**Comment by naoki9911** [comment]
Thank you for your great work!
I've tested the patch in my ipv6 single-stack cluster, but it seems some errors happen.
image
```
rpc error: code = FailedPrecondition desc = Can't access cart storage. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on redis-cart:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 252s ago, v: 2.2.4.27433
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(ConfigurationOptions, TextWriter ) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 879
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.ConnectAsync(CancellationToken )
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String, Boolean, CancellationToken )
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String, CancellationToken )
   at cartservice.cartstore.RedisCartStore.GetCartAsync(String) in /app/cartstore/RedisCartStore.cs:line 104
could not retrieve cart
main.(*frontendServer).homeHandler
	/src/handlers.go:69
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2109
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
main.(*logHandler).ServeHTTP
	/src/middleware.go:82
main.ensureSessionID.func1
	/src/middleware.go:109
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2109
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1991
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
```


It seems cartservice fails to connect to redis server and may be related to the below issues.
https://github.com/StackExchange/StackExchange.Redis/issues/2240
https://github.com/StackExchange/StackExchange.Redis/issues/2277

cartservices uses Cahing.StackExchangeRedis with version 7.0.0.
https://github.com/GoogleCloudPlatform/microservices-demo/blob/e9bc7de0f3ada920c28b9b66c30d2dc9ed0785b5/src/cartservice/src/cartservice.csproj#L10

aspnetcore with .NET 7 uses StackExchangeRedis with version 2.2.4
https://github.com/dotnet/aspnetcore/blob/b9e4f660e6137756de9905b2b3463a9ea6e2de12/eng/Versions.props#L282

The version of StackExchangeRedis is released at Nov 19. 2020, so the fix in https://github.com/StackExchange/StackExchange.Redis/issues/2240 is not applied and the same issue occures.

**Comment by mathieu-benoit** [comment]
Wonderful, thanks for testing and reporting these detailed information, much appreciated!

So yeah, the `StackExchange.Redis` issue was reported in the past (https://github.com/GoogleCloudPlatform/microservices-demo/issues/599) but you confirmed that it is still here. We will need to investigate this further.

So, just to confirm, do you now see that the previous errors related to `0.0.0.0` with `currencyservice`, `emailservice` and `paymentservice` are gone/fixed with this PR?

**Comment by naoki9911** [comment]
Thanks for the quick reply!

> So, just to confirm, do you now see that the previous errors related to 0.0.0.0 with currencyservice, emailservice and paymentservice are gone/fixed with this PR?

Yes, the issue related to listening address seems to be fixed.
At least, services output errors related to cartservices(e.g. failed to connect to redis server)

**Comment by mathieu-benoit** [comment]
Hi @naoki9911, could you give it another try by adding/updating the `cartservice`'s container image to `gcr.io/online-boutique-ci/refs/pull/1340/cartservice:1340` please? Thanks in advance!

**Comment by naoki9911** [comment]
@mathieu-benoit Thanks!
I've tested the patch with newer version of StackExchange.Redis.
It works on my ipv6 single-stack cluster!
Services seem to work correctly, and the loadgenerator says the requests are completed successfully.
I appreciate your great effort on ipv6 single-stack cluster support!

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /                                                                                 28     0(0.00%) |     47      31     101     42 |    0.00        0.00
GET      /cart                                                                             48     0(0.00%) |     39      17     205     28 |    0.10        0.00
POST     /cart                                                                             50     0(0.00%) |     44      24     166     36 |    0.30        0.00
POST     /cart/checkout                                                                    12     0(0.00%) |     75      31     288     41 |    0.00        0.00
GET      /product/0PUK6V6EV0                                                               23     0(0.00%) |     30      20      47     30 |    0.10        0.00
GET      /product/1YMWWN1N4O                                                               25     0(0.00%) |     34      24      86     30 |    0.30        0.00
GET      /product/2ZYFJ3GM2N                                                               27     0(0.00%) |     33      23      53     29 |    0.10        0.00
GET      /product/66VCHSJNUP                                                               29     0(0.00%) |     31      23      72     29 |    0.50        0.00
GET      /product/6E92ZMYYFZ                                                               29     0(0.00%) |     32      20      58     30 |    0.10        0.00
GET      /product/9SIQT8TOJO                                                               30     0(0.00%) |     32      19      79     30 |    0.20        0.00
GET      /product/L9ECAV7KIM                                                               26     0(0.00%) |     36      24     129     30 |    0.30        0.00
GET      /product/LS4PSXUNUM                                                               29     0(0.00%) |     31      22      50     30 |    0.00        0.00
GET      /product/OLJCESPC7Z                                                               16     0(0.00%) |     31      21      49     30 |    0.00        0.00
POST     /setCurrency                                                                      35     0(0.00%) |     58      35     253     46 |    0.30        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                       407     0(0.00%) |     39      17     288     32 |    2.30        0.00
```

**Comment by mathieu-benoit** [comment]
Really great, thanks for your help and collaboration on this, much appreciated!

**Comment by mathieu-benoit** [comment]
Ready for your review, thanks!

**Review by NimJay — APPROVED** [review]
Thanks so much for @mathieu-benoit for adding this functionality to Online Boutique.

And thank you, @naoki9911, for not only testing this on a IPv6 single-stack cluster but also for providing detailed info about the errors you were witnessing! You made this possible.

Approved!

**Pull request merged**
