### PR TITLE
Adding Apigee configuration feature for Apigee demos

### PR DESCRIPTION
**Pull request by phriscage**
I've modified the Hipster Shop with a new **config** feature so users can add an Apigee client ID for Apigee Istio demonstrations. This feature consists of a basic configuration page and custom middleware for the request authorization header. A complete authentication framework for the frontend is TBD

### CODE REVIEW

**Comment by ahmetb** [comment]
I'll review this to understand whether it fits our scope or not.

But next time, please send a proposal first so if it ends up getting rejected, you're not writing the code for nothing.

**Comment by ahmetb** [comment]
From a quick 1-minute look I'm currently -1 for this change.

Ideally vendor-specific stuff that require substantial changes to the application code should not be part of this application. A primary motivator for this demo is "look at this application code, which doesn't look Google-specific at all".

**Comment by phriscage** [comment]
> From a quick 1-minute look I'm currently -1 for this change.
> 
> Ideally vendor-specific stuff that require substantial changes to the application code should not be part of this application. A primary motivator for this demo is "look at this application code, which doesn't look Google-specific at all".

That's fair. The feature will be leveraged for Apigee/GCP specific sessions regardless, so feel free to close if it is not relevant for the main project.

I think a more generic authentication framework would be more appropriate. Where should I submit proposals? Issue **kind/feature** request?

Thanks,
Chris

**Comment by ahmetb** [comment]
I think the authentication goes deep into application development space rather than the focus ("cloud native infrastructure" and modern monitoring practices) of the demo app.

If it wasn't changing the code much, we could potentially support it, but honestly this adds a whole new dimension to the project that we won't have an active maintainer for and test actively.

So I'm inclined to close, but happy to reopen later if any Apigee folks step up to maintain this (and find a middle ground that doesn't require such a large patch).

**Pull request closed without merging**
