### PR TITLE
Update development-guide.md

### PR DESCRIPTION
**Pull request by tdeburca**
Update instructions to show how to check that local deployment has worked correctly.

Tested with:
Windows 10/wsl, 
Docker Desktop w/Kubernetes.

### Background 
This change lets someone following the instructions for local development see the local deploy.

### Change Summary
Doc fix.

### CODE REVIEW

**Comment by tdeburca** [comment]
Completed CLA.

**Comment by xtineskim** [comment]
Hi @tdeburca ! Thanks for opening this pr! 
The port forward step is necessary, so users can access the deployment. Without the `port-forward`, nothing would be "running" in your local host for your browser to hit.
Closing for now, please don't hesitate to re-open and add more detail if I interpreted your description incorrectly.

**Comment by tdeburca** [comment]
Christine,

I'm sorry, I'm relatively new to kubernetes, but I think that's not the
case, Can you check?

I updated the docs after I followed the process and discovered that I
didn't need it.
I don't believe I've done any port forwards and it's working.

To confirm:
From my windows box with Docker acting as the kubernetes cluster:

C:\Users\tdebu>kubectl get service frontend-external
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)
     AGE
frontend-external   LoadBalancer   10.107.131.175   localhost
80:32420/TCP   5d20h

C:\Users\tdebu>kubectl describe service frontend-external
Name:                     frontend-external
Namespace:                default
Labels:
skaffold.dev/run-id=47feacbe-9419-4fba-9012-7d0539986ebe
Annotations:              <none>
Selector:                 app=frontend
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.107.131.175
IPs:                      10.107.131.175
LoadBalancer Ingress:     localhost
Port:                     http  80/TCP
TargetPort:               8080/TCP
NodePort:                 http  32420/TCP
Endpoints:                10.1.0.39:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

Getting a list of port-forwards seems to be a little opaque, so I've
attached the output form get svc --all-namespaces -o json in case that
helps.

As far as I can tell the stanza here:
https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/kubernetes-manifests/frontend.yaml#L110-L121

apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080

Works the same as :
https://www.docker.com/blog/how-kubernetes-works-under-the-hood-with-docker-desktop/

apiVersion: v1
kind: Service
metadata:
  name: tutorial
spec:
  ports:
      - name: 80-tcp
  port: 80
  protocol: TCP
  targetPort: 80
  selector:
com.docker.project: tutorial
  type: LoadBalancer
status:
  loadBalancer: {}

Which is described in the blog as:

> Services of type LoadBalancer are exposed outside the Kubernetes cluster.
> Opening a browser and navigating to localhost:80 displays the Docker
> tutorial.


I hope that makes sense.
Thanks for your patience.
T.

**Comment by xtineskim** [comment]
Ah I understand what you mean - the different ways of deploying locally has different ways for providing the `external ip`. Ideally, we would just have the section that would outline for the different deployment methods that the user followed, or a note such as `Based on your local machine's environment, you may skip this port-forwarding step and access localhost:80 directly`.

**Pull request closed without merging**
