### PR TITLE
Add footer refs to UI for session & request id

### LINKED ISSUE #361: Please restore the `session-id` and `request-id` references
The `session-id` and `request-id` references were removed from the footer (`src/frontend/templates/footer.html`) in v0.2.0 as a part of the "footer cleanup" in https://github.com/GoogleCloudPlatform/microservices-demo/commit/814088f788fd014b433546d4f03e97f148dd2ac8.  Could we restore these?  They were useful to observe (relevant) logs in Cloud Logging.

### PR DESCRIPTION
**Pull request by djmailhot**
Fixes #361 

footer-hipster

### CODE REVIEW

**Comment by ahmetb** [comment]
The layout looks rather odd. 🤔 They used to be on separate lines instead of columns in the footer:

```
Notice
Copyright (Source Code)
<small> session id: xxx - request id: zzz</small>
```

would be great if you can restore that.

**Comment by djmailhot** [comment]
Updated to use a vertical layout.

footer-hipster

**Comment by djmailhot** [comment]
Swapped the notice and copyright lines so they match your suggested layout

```
Notice
Copyright (Source Code)
<small> session id: xxx - request id: zzz</small>
```

**Comment by djmailhot** [comment]
@ahmetb I could use another review on this PR, thanks!

**Review by askmeegs — APPROVED** [review]

**Pull request merged**
