### PR TITLE
cartservice - managed grpc

### PR DESCRIPTION
**Pull request by mathieu-benoit**
- [X] New managed gRPC implementation: https://docs.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-5.0
- [X] Remove start command line and leverage built-in configuration https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#environment-variables
- [X] Container image size from `189MB` to `50.3MB`

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
For information at this stage, container image: `189MB` --> `106MB`.

**Comment by mathieu-benoit** [comment]
For information at this stage, container image: `106MB` --> `40.4MB`.

**Comment by mathieu-benoit** [comment]
For information at this stage, container image: `40.4MB` --> `50.4MB`.

**Comment by mathieu-benoit** [comment]
Ready for your review, thanks!

**Comment by askmeegs** [comment]
This looks great overall, thanks for making these changes! Quick question, I noticed most of the generated proto files, such as `src/cartservice/grpc_generated/Demo.cs`, are removed - can you help me understand why the managed gRPC implementation makes these .pb files no longer needed? 

Looking at this - https://docs.microsoft.com/en-us/aspnet/core/grpc/dotnet-grpc?view=aspnetcore-5.0 
Seems like all it needs is the raw `.proto` file?

**Comment by mathieu-benoit** [comment]
Good question @askmeegs, it's indeed a second approach available with .NET Core, if I recall correctly coming from this: https://grpc.io/blog/grpc-on-dotnetcore/#whats-new:
> Unlike the existing C-Core based implementation (Grpc.Core), the new libraries (grpc-dotnet) make use of the existing networking primitives in the .NET Core Base Class Libraries (BCL). The diagram below highlights the difference between the existing Grpc.Core library and the new grpc-dotnet libraries.

**Comment by askmeegs** [comment]
> Good question @askmeegs, it's indeed a second approach available with .NET Core, if I recall correctly coming from this: https://grpc.io/blog/grpc-on-dotnetcore/#whats-new:
> 
> > Unlike the existing C-Core based implementation (Grpc.Core), the new libraries (grpc-dotnet) make use of the existing networking primitives in the .NET Core Base Class Libraries (BCL). The diagram below highlights the difference between the existing Grpc.Core library and the new grpc-dotnet libraries.
> 
> And yes all it needs is the `.proto` file + `<Protobuf Include="protos\Cart.proto" GrpcServices="Server" />` + `services.AddGrpc();` + `endpoints.MapGrpcService<CartService>();`.
> 
> Let me know if you have any questions or need any complementary information.

makes sense, thank you for clarifying!

**Review by askmeegs — APPROVED** [review]

**Pull request merged**
