### PR TITLE
Remove init container on load gen

### PR DESCRIPTION
**Pull request by howardjohn**
Partial fix for https://github.com/GoogleCloudPlatform/microservices-demo/issues/269

Perfectly understand if we want a fix that preserves the functionality. I am giving a demo with strict mtls so will be using this PR, so figured I would submit it at least

### CODE REVIEW

**Comment by ahmetb** [comment]
Let's revert manifest/**, that's meant to be updated when we have a new tag.

**Comment by ahmetb** [comment]
Let's revert release/**, that's meant to be updated when we have a new tag.

**Comment by askmeegs** [comment]
Suggest maybe closing this one in favor of https://github.com/GoogleCloudPlatform/microservices-demo/pull/279, which removes the init container but also adds a single curl to the beginning of the loadgen src? 
(sorry, just saw this @howardjohn !)

**Comment by askmeegs** [comment]
Closing in favor of #279 which was merged.

**Pull request closed without merging**
