### PR TITLE
Updating httplib2 to 0.19.0

### PR DESCRIPTION
**Pull request by donmccasland**
### Background 
Fixing dependabot alert

### Change Summary
Updates httplib2 to 0.19.0

### CODE REVIEW

**Comment by ckim328** [comment]
I don't see any changes to the `requirements.in` file; I ran into this with https://github.com/GoogleCloudPlatform/microservices-demo/pull/695#pullrequestreview-861588766 
tl;dr,  instead use the `requirements.in` as input to `pip-compile`!

**Comment by NimJay** [comment]
Thanks for catching the missing `requirements.in` updates, @ckim328!

I'm also wondering why there is no comment from GitHub actions (e.g., [like this one](https://github.com/GoogleCloudPlatform/microservices-demo/pull/709#issuecomment-1032793599)) containing the staging URL.
In the meantime, the staging URL for this pull-request can be found in [the GitHub Action logs](https://github.com/GoogleCloudPlatform/microservices-demo/runs/5113057234?check_suite_focus=true): http://34.123.56.89 (which seems to be working!)

**Comment by donmccasland** [comment]
> Thanks for catching the missing `requirements.in` updates, @ckim328!
> 
> I'm also wondering why there is no comment from GitHub Actions (e.g., [like this one](https://github.com/GoogleCloudPlatform/microservices-demo/pull/709#issuecomment-1032793599)) containing the staging URL. In the meantime, the staging URL for this pull-request can be found in [the GitHub Action logs](https://github.com/GoogleCloudPlatform/microservices-demo/runs/5113057234?check_suite_focus=true): http://34.123.56.89 (which seems to be working!)

No requirements.in did not change.  Just re-running pip-compile gave us an updated httplib2

**Review by bourgeoisor — APPROVED** [review]
LGTM

**Pull request merged**
