### PR TITLE
README.md: add GCP-runnable version from Github

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there,

I recently created the linked repo to implement a Github automated workflow deploying Online Boutique with some standard tools for such a service mesh: Istio, Kiali, Prometheus, Grafana, Jaeger, etc. so that people get right away a complete demo/testbed close to "real life".

As you'll see in stars and forks, it raises quite some interest. So, I thought that it would be worth adding to the implementation featuring Online Boutique. I will keep it up to date when new versions of Online Boutique and tools are published.

Please, feel free to amend my proposed text if you accept this PR.

Best regards,

Didier

### CODE REVIEW

**Comment by ahmetb** [comment]
Excellent work there. 
It's likely we have quite a few non-trivial forks (I personally see many internally as well as at conference floors), so I am not sure if it'll be a consistent or maintained list if we start doing that.

**Comment by didier-durand** [comment]
@ahmetb : thanks for the appreciation. My goal in doing this was to offer a very easy entry into the world of microservices and service mesh to new comers. If you look at the comment on [this](https://www.reddit.com/r/devops/comments/j38n2w/10_docker_containers_in_a_service_mesh_online/) and [that](https://www.reddit.com/r/googlecloud/comments/iyvoqk/microservice_application_with_istio_kiali_jaeger/) subs on Reddit, it seems to be quite appreciated. But, up to you to decide as owner. 

Best
Didier

**Comment by djmailhot** [comment]
With a developer hat on, having access to a complete example demo/testbed close to "real life" is awesome.  Thanks for putting that work together Didier!

With the repo maintainer hat on, I don't think we want to be in the business of keeping track of a list of alternative repos featuring variations on the material.  Additionally, if we were to list a few third-party repos, it could be interpreted that we are endorsing those few repos above all the other thousands of forks of Online Boutique.

So, closing this PR for now.

**Comment by didier-durand** [comment]
@djmailhot : I fully understand your view on this. Anyway, thanks for the positive feedback.  Best, Didier

**Pull request closed without merging**
