### PR TITLE
Remove deps files from node paymentservice

### PR DESCRIPTION
**Pull request by bvwells**
Remove deps files from node paymentservice.

### CODE REVIEW

**Comment by bvwells** [comment]
Apologies if I'm missing something, but I can't imagine that a node service requires deps files...

**Comment by ahmetb** [comment]
Haha I'm not at all sure how this happened.
Maybe dep has detected it's a Go package directory somehow.

**Comment by bvwells** [comment]
Glad I wasn't missing something! :-)

**Comment by bvwells** [comment]
Thanks for the review and merge @ahmetb!

**Pull request merged**
