### PR TITLE
add delay to adservice readiness probe.

### LINKED ISSUE #189: adservice sometimes crashlooping when deployed locally (due to slow startup)
When deployed locally (i.e. docker for mac or something like that) `adservice` is crashlooping.

cc: @rghetia  @sebright I'm not sure if this has anything to do with recent logging additions.

The reason is that the health RPC (1) isn't responding within 1 second and sometimes (2) the port :9555 isn't listening:

```
  Warning  Unhealthy              39m (x6 over 41m)     kubelet, docker-for-desktop  Liveness probe failed: timeout: failed to connect service ":9555" within 1s
  Warning  Unhealthy              31m (x14 over 41m)    kubelet, docker-for-desktop  Readiness probe failed: timeout: failed to connect service ":9555" within 1s
  Warning  Unhealthy              11m (x3 over 39m)     kubelet, docker-for-desktop  Readiness probe failed: timeout: health rpc did not complete within 1s
```

Did we add something to the startup sequence that would delay the RPC handling becoming ready?

Here are the logs from pod (I see no errors, but eventually a graceful shutdown happens).

```
{"thread":"main","level":"INFO","loggerName":"hipstershop.AdService","message":"Jaeger initialization disabled.","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552503347,"nanoOfSecond":555000000},"threadId":1,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T18:55:47.555Z"}
{"thread":"main","level":"INFO","loggerName":"hipstershop.AdService","message":"AdService starting.","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552503352,"nanoOfSecond":839000000},"threadId":1,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T18:55:52.839Z"}
{"thread":"Thread-1","level":"INFO","loggerName":"hipstershop.AdService","message":"Initialize StackDriver","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552503347,"nanoOfSecond":555000000},"threadId":12,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T18:55:47.555Z"}
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{"thread":"Thread-1","level":"INFO","loggerName":"hipstershop.AdService","message":"Attempt to register Stackdriver Exporter in 10 seconds ","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552503367,"nanoOfSecond":483000000},"threadId":12,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T18:56:07.483Z"}
{"thread":"main","level":"INFO","loggerName":"hipstershop.AdService","message":"Ad Service started, listening on 9555","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552503369,"nanoOfSecond":249000000},"threadId":1,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T18:56:09.249Z"}
*** shutting down gRPC ads server since JVM is shutting down
*** server shut down
```

### PR DESCRIPTION
**Pull request by rghetia**
fixes #189

### CODE REVIEW

**Comment by ahmetb** [comment]
I think 20 seconds is already a very high delay, we shouldn't increase this further.

First, I'm trying to understand from the logs why is it taking so long for server to start. If you have any ideas let know, I'm suspecting if any of the Stackdriver retries are blocking the server listening for 30s.

**Comment by ahmetb** [comment]
I made the readiness probe delay 70 seconds locally, still failing. But other services started to fail at the same time. I'll keep adding more CPUs to see when it will run reliably. Something must be hogging the CPU of my docker-for-desktop instance.

Let's hold until we figure this out. I'm guessing this PR is not necessary.

**Comment by rghetia** [comment]
Stackdriver is retrying on separate thread so it should not block the main thread.
on my mac it starts listening in 6 seconds.
```
{"thread":"Thread-1","level":"INFO","loggerName":"hipstershop.AdService","message":"Initialize StackDriver","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552513739,"nanoOfSecond":118000000},"threadId":13,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T21:48:59.118Z"}
{"thread":"main","level":"INFO","loggerName":"hipstershop.AdService","message":"Jaeger initialization disabled.","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552513739,"nanoOfSecond":118000000},"threadId":1,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T21:48:59.118Z"}
{"thread":"main","level":"INFO","loggerName":"hipstershop.AdService","message":"AdService starting.","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552513741,"nanoOfSecond":220000000},"threadId":1,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T21:49:01.220Z"}
{"thread":"main","level":"INFO","loggerName":"hipstershop.AdService","message":"Ad Service started, listening on 9555","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552513746,"nanoOfSecond":836000000},"threadId":1,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T21:49:06.836Z"}
{"thread":"Thread-1","level":"INFO","loggerName":"hipstershop.AdService","message":"StackDriver initialization complete.","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.spi.AbstractLogger","instant":{"epochSecond":1552513785,"nanoOfSecond":931000000},"threadId":13,"threadPriority":5,"logging.googleapis.com/trace":"00000000000000000000000000000000","logging.googleapis.com/spanId":"0000000000000000","logging.googleapis.com/traceSampled":"false","time":"2019-03-13T21:49:45.931Z"}
```

**Comment by ahmetb** [comment]
I'm convinced this is docker-for-mac VM on my machine being exceptionally slow for some reason. We shouldn't increase the delays. Thanks for the PR/investigation though. 🙌

**Pull request closed without merging**
