### PR TITLE
pb: add "categories" field to Product

### PR DESCRIPTION
**Pull request by sebright**
This field can be used as the context keys to look up relevant ads in the ad
service.

/cc @rghetia 

I also ran the genproto.sh scripts for the Java and Go services and included those changes in the second commit.  I encountered an issue when I ran genproto.sh for the recommendation service, and I'm still looking into it.

### CODE REVIEW

**Comment by ahmetb** [comment]
> I encountered an issue when I ran genproto.sh for the recommendation service, and I'm still looking into it.

Is this still the case? Rest of the patch is LGTM.

**Comment by sebright** [comment]
@ahmetb I haven't been able to fix the problem.  I keep getting this error at runtime:

```
Traceback (most recent call last):
  File "/recommendationservice/recommendation_server.py", line 25, in <module>
    import demo_pb2
  File "/recommendationservice/demo_pb2.py", line 22, in <module>
    2\x41\x64\x12\x14\n\x0credirect_url\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xca\x01\n\x0b\x43\x61rtService\x12<\n\x07\x41\x64\x64Item\x12\x1b.hipstershop.AddItemRequest\x1a\x12.hipstershop.Empty\"\x00\x12;\n\x07GetCart\x12\x1b.hipstershop.GetCartRequest\x1a\x11.hipstershop.Cart\"\x00\x12@\n\tEmptyCart\x12\x1d.hipstershop.EmptyCartRequest\x1a\x12.hipstershop.Empty\"\x00\x32\x83\x01\n\x15RecommendationService\x12j\n\x13ListRecommendations\x12\'.hipstershop.ListRecommendationsRequest\x1a(.hipstershop.ListRecommendationsResponse\"\x00\x32\x83\x02\n\x15ProductCatalogService\x12G\n\x0cListProducts\x12\x12.hipstershop.Empty\x1a!.hipstershop.ListProductsResponse\"\x00\x12\x44\n\nGetProduct\x12\x1e.hipstershop.GetProductRequest\x1a\x14.hipstershop.Product\"\x00\x12[\n\x0eSearchProducts\x12\".hipstershop.SearchProductsRequest\x1a#.hipstershop.SearchProductsResponse\"\x00\x32\xaa\x01\n\x0fShippingService\x12I\n\x08GetQuote\x12\x1c.hipstershop.GetQuoteRequest\x1a\x1d.hipstershop.GetQuoteResponse\"\x00\x12L\n\tShipOrder\x12\x1d.hipstershop.ShipOrderRequest\x1a\x1e.hipstershop.ShipOrderResponse\"\x00\x32\xb7\x01\n\x0f\x43urrencyService\x12[\n\x16GetSupportedCurrencies\x12\x12.hipstershop.Empty\x1a+.hipstershop.GetSupportedCurrenciesResponse\"\x00\x12G\n\x07\x43onvert\x12&.hipstershop.CurrencyConversionRequest\x1a\x12.hipstershop.Money\"\x00\x32U\n\x0ePaymentService\x12\x43\n\x06\x43harge\x12\x1a.hipstershop.ChargeRequest\x1a\x1b.hipstershop.ChargeResponse\"\x00\x32h\n\x0c\x45mailService\x12X\n\x15SendOrderConfirmation\x12).hipstershop.SendOrderConfirmationRequest\x1a\x12.hipstershop.Empty\"\x00\x32\x62\n\x0f\x43heckoutService\x12O\n\nPlaceOrder\x12\x1e.hipstershop.PlaceOrderRequest\x1a\x1f.hipstershop.PlaceOrderResponse\"\x00\x32H\n\tAdService\x12;\n\x06GetAds\x12\x16.hipstershop.AdRequest\x1a\x17.hipstershop.AdResponse\"\x00\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

I searched online and found a suggestion to downgrade protoc to 3.4.0, but that didn't seem to affect the generated code.  Do you know what version of protoc is required for regenerating the Python protocol buffer code?  I'm also wondering if a version mismatch is affecting the Go generated code in this PR, because the diff is surprisingly large.

**Comment by ahmetb** [comment]
Hmm I have no idea what version of protoc or grpc plugin we used to generate the code but it should not matter.

Maybe revert changes and only generate services that are affected by this field? Adding a new field should not be requiring regeneration for recommendationservice.

**Comment by sebright** [comment]
Thanks.  I reverted all generated code changes, except for changes to adservice, frontend, and productcatalogservice.  I initially thought that I needed to update all services just to keep them up to date.

**Pull request merged**
