### PR TITLE
Change 'wait' to use 'between' as recommended by locustio

### PR DESCRIPTION
**Pull request by jorgonzalez**
See https://github.com/locustio/locust/pull/1118

### CODE REVIEW

**Comment by ahmetb** [comment]
Do we need to update locust version?

**Comment by jorgonzalez** [comment]
> Do we need to update locust version?

Yes, to https://github.com/locustio/locust/releases/tag/0.13.0

> New API for specifying wait time #1118 (heyman)

**Comment by ahmetb** [comment]
Got it, so you probably should follow https://github.com/GoogleCloudPlatform/microservices-demo/blob/ccff406cdcd3e043b432fe99b4038d1b4699c702/src/loadgenerator/requirements.txt#L1-L6 as well , otherwise this patch is just breaking things. 

It would be also great if you can deploy this app locally and verify locust works fine.

**Comment by jorgonzalez** [comment]
Requirement files updated. Couldn't build since I don't have permissions to activate 'Google Cloud Build' in my project and I got the "No space left on device" error on Google Cloud Shell. Sorry.

**Comment by jorgonzalez** [comment]
> tACK; tested on my local k8s cluster smile
> 
> ```
> + STATUSCODE=200
> + test 200 -ne 200
> + locust --host=http://frontend:80 --no-web -c 10
> [2020-03-22 13:48:02,668] loadgenerator-55f89bf794-6vxb8/INFO/locust.main: Starting Locust 0.13.0
> [2020-03-22 13:48:02,669] loadgenerator-55f89bf794-6vxb8/INFO/locust.runners: Hatching and swarming 10 clients at the rate 1 clients/s...
> ```

Thanks, I hope this gets merged soon.

**Comment by ahmetb** [comment]
Thanks!

**Pull request merged**
