### PR TITLE
Use buildkit by default

### PR DESCRIPTION
**Pull request by inductor**
This repo's base images use multi stage build and I think it should be better to make the build faster by BuildKit.

### CODE REVIEW

**Comment by ahmetb** [comment]
I'm not sure about the compatibility outcomes of this.

**Comment by inductor** [comment]
@ahmetb 
Based on the Skaffold source code, it adds the environment variable.
https://github.com/GoogleContainerTools/skaffold/blob/17e1e021b7e68ee57c717c1c22e06e48c68403a9/pkg/skaffold/build/local/docker.go#L89

```go
	if b.cfg.UseBuildkit {
		cmd.Env = append(cmd.Env, "DOCKER_BUILDKIT=1")
	}
```

It does not break anything where you don't have BuildKit capability on your Docker host.

**Comment by ahmetb** [comment]
Makes me wonder, why then the Skaffold doesn't do it by default?

**Comment by inductor** [comment]
Um I think that is because Docker hasn't set it by default?

**Review by djmailhot — APPROVED** [review]
Seems to improve build time by 50% (from ~3m to ~2m).  Promises only to be run if buildkit is available.

Passes CI tests on internal branch.

**Pull request merged**
