### PR TITLE
Loadgenerator :: Dockerfile :: Fix, --prefix support issue

### PR DESCRIPTION
**Pull request by omergulen**
A solution to #386.

### CODE REVIEW

**Comment by omergulen** [comment]
@googlebot I signed it!

**Comment by omergulen** [comment]
Pinging old reviewers since the issue is a **blocker**.

@Daniel-Sanche @ahmetb @sadikkuzu

**Comment by omergulen** [comment]
Sorry for mis-categorizing it then. Thank you for your review @ahmetb.

**Review by degemenc — APPROVED** [review]
This has worked for me as well.

**Pull request merged**
