### PR TITLE
Fix the NuGet error

### PR DESCRIPTION
**Pull request by ChakshuGupta**
Fixes the following error which is coming due to changes in Microsoft's CA signing changes.
[https://github.com/NuGet/Announcements/issues/49](https://github.com/NuGet/Announcements/issues/49)

```
app/cartservice.csproj : error NU3028: Package 'Microsoft.Extensions.Logging.Abstractions 3.0.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/cartservice.csproj : error NU3037: Package 'Microsoft.Extensions.Logging.Abstractions 3.0.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/app/cartservice.csproj : error NU3028: Package 'Microsoft.Extensions.Logging.Abstractions 3.0.3' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/cartservice.csproj : error NU3028: Package 'System.Threading.Channels 4.6.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/cartservice.csproj : error NU3037: Package 'System.Threading.Channels 4.6.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/app/cartservice.csproj : error NU3028: Package 'System.Threading.Channels 4.6.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/cartservice.csproj : error NU3028: Package 'System.Diagnostics.PerformanceCounter 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/cartservice.csproj : error NU3037: Package 'System.Diagnostics.PerformanceCounter 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/app/cartservice.csproj : error NU3028: Package 'System.Diagnostics.PerformanceCounter 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
```

Change summary:
 From:
 `FROM mcr.microsoft.com/dotnet/sdk:5.0.102 as builder `
 To:
` FROM mcr.microsoft.com/dotnet/sdk:5.0-focal as builder`

Remaining issues / concerns:
This is just a workaround for now. Will require changes when the new version comes out.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Thanks @ChakshuGupta, we indeed faced this yesterday with @askmeegs. According to this new temporary patch explained https://github.com/NuGet/Announcements/issues/49#issuecomment-768766265 with this image `5.0.102-ca-patch-buster-slim`. Do you think we should use it insted of the `focal` one?

**Comment by mathieu-benoit** [comment]
After a quick chat with @askmeegs, we would love to move forward with the official temporary fix with `5.0.102-ca-patch-buster-slim`. @ChakshuGupta, do you want to update your branch/PR with this, or do you want us creating a new branch/PR with this? Thanks again for your contribution!

**Comment by ChakshuGupta** [comment]
I'll update my branch.

**Comment by ChakshuGupta** [comment]
@mathieu-benoit I have made the required changes.

**Comment by askmeegs** [comment]
Thank you for your help, Chakshu and Mathieu! :)

**Pull request merged**
