### PR TITLE
add space in comment

### LINKED ISSUE #451: need space in comment for adservice deployment
space are needed in comment for adservice deployment.

**before**
```
        #- name: JAEGER_SERVICE_ADDR
        #  value: "jaeger-collector:14268"
```

**after**
```
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
```

### PR DESCRIPTION
**Pull request by jmyung**
Fixes #451 

Change summary:
**before**
```
        #- name: JAEGER_SERVICE_ADDR
        #  value: "jaeger-collector:14268"
```

**after**
```
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
```

### CODE REVIEW

**Comment by jmyung** [comment]
> ERROR: (gcloud.container.clusters.get-credentials) argument --zone/-z: expected one argument

I need help for deloyment test.
Please let me know a guide or sth.

**Comment by askmeegs** [comment]
Thanks for this PR! We've fixed the problem causing the deployment-tests to fail on forked PRs. Could you please merge upstream/master and push to your branch, in order to rekick the tests? Thank you!

**Comment by askmeegs** [comment]
Hi Jesang, sorry about the delay on this PR. Our CI/CD updates since you put out this PR are breaking the build, but your change is fine - I'm going to put out a separate PR for this, and close this one. Thank you!

**Pull request closed without merging**
