### PR TITLE
Update Currency service to use a http service

### PR DESCRIPTION
**Pull request by mukundha**
Fix for this issue: https://github.com/GoogleCloudPlatform/microservices-demo/issues/80

### CODE REVIEW

**Comment by ahmetb** [comment]
We definitely shouldn’t change it to a service that’ll have shorter lifetime than the one we already have.

What’s the rationale for pointing it to your demo endpoint rather than hardcoding the conversion values into the service?

Since people give keynote demos with this app, unfortunately we can’t point it to your demo app.

**Comment by mukundha** [comment]
Good points @ahmetb 
1 -  think would be useful to externalize the currency URL from the code, 
2 - we need a http service, so I proxied the original service using Apigee,  I will probably setup dedicated environment with hipster CNAME -would that work?
3 - i think having a egress rule for this service has value for istio demos and egress policies, hence did not hardcode the conversion values in the service

**Comment by ahmetb** [comment]
> 2 - we need a http service, so I proxied the original service using Apigee, I will probably setup dedicated environment with hipster CNAME -would that work?

I don't think so, unless you're committed to support this service officially for O(N) years.

> 1 - think would be useful to externalize the currency URL from the code,

We literally have 1 external dependency, and it broke in the first 3 months. While I agree, something like this has potentially turn a keynote demo into a complete catastrophe. Since we used this demo for at least 5 keynotes in the past 3 months, I'm hesitant now.

> 3 - i think having a egress rule for this service has value for istio demos and egress policies,

I agree, but this demo app demonstrates much more important aspects of Istio (like Telemetry, mTLS, metrics etc) and not so much of the Egress rules. Unfortunately I don't think we can have it all. It was good while it lasted, now we have a broken demo in our hands.

**Comment by mukundha** [comment]
makes sense, i will close this PR

**Pull request closed without merging**
