### PR TITLE
Upgrade Golang microservices to Go 1.18.0

### PR DESCRIPTION
**Pull request by NimJay**
### Background 
* [renovate-bot](https://github.com/renovate-bot) created a pull-request to upgrade the versino of Go being used by Go microservices: https://github.com/GoogleCloudPlatform/microservices-demo/pull/779
* But in addition to updating the Dockerfiles, we need to update the `go.mod` files and `go.sum` files.

### Change Summary
* Upgrade the version of Go being used by all 4 Go microservices.

  * Modify base images in Dockerfiles. 
  * Modify `go.mod` files.
  * Regenerate `go.sum` files using [`go mod tidy`](https://go.dev/ref/mod#go-mod-tidy). 

### Additional Notes
* I have tested this on my own GKE cluster using `skaffold`. 👍 

### How to Review
* [ ] Check that this pull-request covers the same files as a [previous Go upgrade](https://github.com/GoogleCloudPlatform/microservices-demo/pull/670/files).
* [ ] Verify that we covered the [full list of Go microservices](https://github.com/GoogleCloudPlatform/microservices-demo#architecture).
* [ ] Smoke test the staging URL.
* [ ] Make sure all checks have passed.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Wow, latest and greatest of Go!

Out of curiosity, does this [CI agent's `install-dependencies`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/.github/workflows/install-dependencies.sh#L41) need to be updated too (for botht that file and the actual agents)?

**Comment by ckim328** [comment]
💯 🔥 
follow up with Mathieu's question, perhaps we should also bump the CI tests as well?
https://github.com/GoogleCloudPlatform/microservices-demo/blob/7ff77e821526b42a88a136d84028c4690a799af5/.github/workflows/ci-pr.yaml#L33

**Comment by NimJay** [comment]
Thanks for catching that (and the speedy review), Mathieu and Christine!
I will work on updating the CI and `install-dependancies` script. :)

**Comment by NimJay** [comment]
1. I have updated `ci-pr.yaml` to use Golang 1.18.0.
2. I have updated `install-dependencies.sh` (script used for setting up new GitHub Action runners) such that it now downloaded Golang 1.18.0.
3. I have run the following in our [2 existing GitHub Action Runner GCE virtual machines](https://pantheon.corp.google.com/compute/instances?referrer=search&project=online-boutique-ci&supportedpurview=project):
```bash
sudo rm -rf /usr/local/go # Remove existing Go installations.
wget https://go.dev/dl/go1.18.linux-amd64.tar.gz # Download Go 1.18.
sudo tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz # Install Go 1.18.
rm go1.18.linux-amd64.tar.gz # Clean up.
```
Commands inspired by the [Go official install page](https://go.dev/doc/install).

**Comment by mathieu-benoit** [comment]
LGTM

**Review by mathieu-benoit — APPROVED** [review]
LGTM

**Pull request merged**
