### PR TITLE
make recommendation service optional

### PR DESCRIPTION
**Pull request by katzio**
### Background 
make recommendation service optional like ad

### Change Summary
Frontend template already supports missing recommendations, removed `renderHTTPError` but kept logs

### Additional Notes
should I add (error) log to [placeOrderHandler](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/frontend/handlers.go#L362)?

### Testing Procedure
Manually: turn off recommendations pod

### Related PRs or Issues 
addressing https://github.com/GoogleCloudPlatform/microservices-demo/issues/1165

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Thanks for taking to initiative and opportunity to fix this, @katzio. Much appreciated!

**Review by mathieu-benoit — APPROVED** [review]
I haven't tested myself, but this LGTM!

We want the same behavior as `adservice`, and I can see that you did the exact same code like here https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/src/frontend/handlers.go#L432.

Thanks again!

Before merging, let's have a final review by @NimJay on this.

**Comment by mathieu-benoit** [comment]
Actually, I just tested in our test environment (for this PR), and we could see that there is no error anymore on the Product page is `recommendationservice` is scaled to 0 pods, see screenshot.
image

**Review by NimJay — APPROVED** [review]
@katzio, thanks so much for looking into this and implementing it.
I didn't think the change would be this simple.
This is great!

@mathieu-benoit, thank you for taking down the `recommendationservice` of the staging deployment. It worked!

Approved. Merging!

**Pull request merged**
