### PR TITLE
Update GitHub action `setup-dotnet@v3` in CIs

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Update GitHub action `setup-dotnet@v3` in CIs.

More information [here](https://github.com/actions/setup-dotnet/releases/tag/v3.0.0) about the removal of the parameter `include-prerelease`.

Fixing issue in https://github.com/GoogleCloudPlatform/microservices-demo/pull/1117

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
There is an issue while upgrading to `v3`: https://github.com/actions/setup-dotnet/issues/327

**Review by minherz — APPROVED** [review]

**Comment by minherz** [comment]
@mathieu-benoit it looks like the current workflow does not support installing dotnet using new action's version. the test shows multiple "access denied" errors.

**Comment by mathieu-benoit** [comment]
Still getting same error:
```
Error: Failed to install dotnet 1. dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
```
Looking at https://github.com/actions/setup-dotnet/issues/327 to see what we need to do.

**Review by bourgeoisor — APPROVED** [review]
LGTM

**Pull request merged**
