### PR TITLE
Use env in service manifests for PORT

### PR DESCRIPTION
**Pull request by jan25**
Supply service ports through env PORT variable in service manifests. Fixes issue: https://github.com/GoogleCloudPlatform/microservices-demo/issues/163

### CODE REVIEW

**Comment by ahmetb** [comment]
Thanks a lot!
Does the cartservice not need any changes?

**Comment by jan25** [comment]
Cartservice looks good. No changes needed for that w.r.t the PORT issue.
And, any hints why Travis-ci errored? I couldn't figure much from the logs. Looks like build failed due to timeout?

**Comment by ahmetb** [comment]
I will restart the build. Travis tends to have a lot of flakiness towards Google Code servers.

**Comment by ahmetb** [comment]
Thanks a lot for making this patch!

**Pull request merged**
